repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run --project beam-python ruff check --fix
        language: system
        types: [python]
        files: ^beam-python/

      - id: ruff-format
        name: ruff-format
        entry: uv run --project beam-python ruff format
        language: system
        types: [python]
        files: ^beam-python/

      - id: pyright
        name: pyright
        entry: uv run --project beam-python pyright
        language: system
        types: [python]
        pass_filenames: false
        files: ^beam-python/
